# Generated by Django 5.0.6 on 2024-05-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookinstance", name="language",),
    ]
